 # Dockerfile pour l'application Streamlit
FROM python:3.9

WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY src/ /app/src

CMD ["streamlit", "run", "/app/src/streamlit_app.py"]
